services:
  - type: web
    name: light-textiles
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
